apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-jrydasqk
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-jrydasqk:5c40d5d279cd30b26eabd36989c3936ef2421d06@sha256:772d25572832780b6d7d99d81048d491c1bb42f667417e2d10c061f0b7e00ef9
          name: container-image
